amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.005
    alpha2: 0.005
    alpha3: 0.01
    alpha4: 0.005
    base_frame_id: "mobile_base_body_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 100
    max_particles: 10000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.2
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.95
    z_max: 0.05
    z_rand: 0.05
    z_short: 0.05
    map_topic: map
    scan_topic: laser
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: -0.8794
      y: -2.2901
      z: 0.0
      yaw: -2.9978

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

amcl_map_client:
  ros__parameters:
    use_sim_time: True


